### ISSUE TITLE
User Report: Invalid Billing is inaccurate

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#262] opened 2017-03-07 17:57 UTC
At /staff/user/user_reports/
- View Report with drop-down menu selecting "Users with Invalid Billing"
- This captures users who also have valid billing.

**Comment by jsayles** [comment] 2017-03-07 18:44
Duplicate of #233.  This report should be removed because it's misleading.

**Closed by jsayles** 2017-03-07 18:44 UTC

**Comment by mimorita** [comment] 2017-03-07 18:50
Not a duplicate, different issue (at least from my perspective). 
The "Invalid Billing" report returns users who have "Valid" in the billing column.
