### ISSUE TITLE
New User emails not being sent

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#382] opened 2018-02-15 17:21 UTC
New user emails are not being sent to team@

**Comment by susancevans** [comment] 2018-02-23 21:04
Now they're being sent but it appears they're coming in multiple times. Member Z C W just signed up as a Resident member starting 2/26 and the email sent three times.

**Comment by jsayles** [comment] 2018-02-28 17:22
This is a duplicate of #352

**Closed by jsayles** 2018-02-28 17:22 UTC
