### ISSUE TITLE
New user does not trigger automated tasks

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#330] opened 2017-07-24 17:44 UTC
This morning about 9:15, P.K. entered his information on the iPad to create a new user. 

- "New user" announcement email did not get sent to team@

**Comment by jsayles** [comment] 2017-07-25 17:22
Duplicate of #313

**Closed by jsayles** 2017-07-25 17:22 UTC

**Comment by susancevans** [comment] 2017-08-07 17:37
This is still not happening. I'm not sure if I need to re-open this or #313 but is there any chance we could prioritize this this week? It's a pretty important feature for us for the day-to-day.

**Comment by jsayles** [comment] 2017-08-07 19:05
The bug is still open but I thought I fixed it.  I'll dig further.

**Comment by susancevans** [comment] 2017-08-07 20:39
Thank you!

__
Office Nomads
officenomads.com
